apiVersion: v2
name: dawarich
version: 10.0.3
kubeVersion: ">=1.19.0-0"

home: https://dawarich.app/
sources:
- https://github.com/Freika/dawarich

dependencies:
- name: redis-ha
  version: 4.35.7
  repository: https://dandydeveloper.github.io/charts
  condition: redis.enabled
  alias: redis
