apiVersion: v2
name: dawarich
version: 9.0.0
kubeVersion: ">=1.19.0-0"

home: https://dawarich.app/
sources:
- https://github.com/Freika/dawarich

dependencies:
- name: redis
  version: 23.2.12
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
