apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 9000
      port: 9000
      protocol: TCP
  selector: {{ include "common.selectorLabels" . | nindent 4 }}
