apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "common.fullname" . }}-init-secret-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/component: "app-init-secret-job"
    {{- include "common.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "app-init-secret-job"
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: secret-init
          image: docker.io/bitnami/kubectl:1.33.4
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - "-c"
            - |
              kubectl get secret {{ template "common.fullname" . }}-secret -n {{ .Release.Namespace }} --allow-missing-template-keys=false -o jsonpath="{.data.secret-key-base}" >/dev/null 2>&1 || \
              kubectl create secret generic {{ template "common.fullname" . }}-secret -n {{ .Release.Namespace }} --from-literal=secret-key-base=$(openssl rand -hex 64) --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: OnFailure
      serviceAccountName: {{ template "common.fullname" . }}-init-secret-job
