apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "common.fullname" . }}-init-secret-job
  labels:
    app.kubernetes.io/component: "app-init-secret-job"
    {{- include "common.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]
