apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}-init-secret-job
  labels:
    app.kubernetes.io/component: "app-init-secret-job"
    {{- include "common.labels" . | nindent 4 }}
