apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.fullname" . }}-init-secret-job
  labels:
    app.kubernetes.io/component: "app-init-secret-job"
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.fullname" . }}-init-secret-job
subjects:
  - kind: ServiceAccount
    name: {{ template "common.fullname" . }}-init-secret-job
    namespace: {{ .Release.Namespace }}
