

image:
  repository: hvxl/otmonitor
  tag: latest
  sha: sha256:d060793406684e047f623324df8fe92543d630080b0bbce0832d4ab1d74969e8

route:
  enabled: false
  apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  annotations: {}
  hostnames:
    - opentherm-monitor.example.com
  parentRefs: []
  filters: []
  matches: []
  timeouts: {}

nodeSelector:
  beta.kubernetes.io/arch: amd64 # image is only available for amd64, not arm64

persistence:
  size: 1Gi
#  storageClass:
