{{- if and .Values.app.persistence.enabled (not .Values.app.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-storage
  labels:
    app.kubernetes.io/component: "app"
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}
{{- end }}
