apiVersion: v2
name: immich
version: 10.2.0
kubeVersion: ">=1.19.0-0"

home: https://immich.app
sources:
- https://github.com/immich-app/immich

dependencies:
- name: redis-ha
  version: 4.35.5
  repository: https://dandydeveloper.github.io/charts
  condition: redis.enabled
  alias: redis
