apiVersion: v2
name: immich
version: 10.0.0
kubeVersion: ">=1.19.0-0"

home: https://immich.app
sources:
- https://github.com/immich-app/immich

dependencies:
- name: redis
  version: 24.0.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
